### ISSUE TITLE
Post-merge TODO list

### ISSUE THREAD

**Issue by scrdest** [UristMcStation/UristMcStation#293]
- [x] Maybe restore Ravensdale borg sprites.
- [x] Check all the copypasta'd light amount checks in the new system. Maybe proc them properly.
- [x] Considering grown.dm got eaten by the daemons lurking in the Merge, check if other hydro code wasn't chewed on.
- [x] Vampires can drain monkeys. Not sure if it shouldn't be made into a feature...
- [x] Humanoids seem to have a lot more blood than pre-update; 180 vs. 120-ish; rebalance if needed... but I actually kinda like the idea
- [ ] fix the easels
- [ ] fix emplacements
- [x] port over the stuff from Glloyd's other branch (?)

**Comment by CPU-Blanc** [comment]
Is this still relevant at this point? :P

**Comment by Glloyd** [comment]
easels and emplacements haven't worked since 2015 and at this point i don't even think the code is still around. we can close this.
